package com.lab.app.ketman.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.lab.app.ketman.mybatis.domain.Reply;
import com.lab.app.ketman.mybatis.domain.ReplyExample;

@Mapper
public interface ReplyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbg.generated  Tue Oct 22 22:40:48 JST 2019
	 */
	long countByExample(ReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbg.generated  Tue Oct 22 22:40:48 JST 2019
	 */
	int deleteByExample(ReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbg.generated  Tue Oct 22 22:40:48 JST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbg.generated  Tue Oct 22 22:40:48 JST 2019
	 */
	int insert(Reply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbg.generated  Tue Oct 22 22:40:48 JST 2019
	 */
	int insertSelective(Reply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbg.generated  Tue Oct 22 22:40:48 JST 2019
	 */
	List<Reply> selectByExample(ReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbg.generated  Tue Oct 22 22:40:48 JST 2019
	 */
	Reply selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbg.generated  Tue Oct 22 22:40:48 JST 2019
	 */
	int updateByExampleSelective(@Param("record") Reply record, @Param("example") ReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbg.generated  Tue Oct 22 22:40:48 JST 2019
	 */
	int updateByExample(@Param("record") Reply record, @Param("example") ReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbg.generated  Tue Oct 22 22:40:48 JST 2019
	 */
	int updateByPrimaryKeySelective(Reply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbg.generated  Tue Oct 22 22:40:48 JST 2019
	 */
	int updateByPrimaryKey(Reply record);
}